### ISSUE TITLE
No module named "CloudFlare"

### ISSUE THREAD

**Issue by yaba** [Glocktober/cfspflat#2]
```
Traceback (most recent call last):
  File "/home/dietpi/cfspflat/app.py", line 3, in <module>
    from cfspflat.cli import main
  File "/home/dietpi/cfspflat/cfspflat/__init__.py", line 7, in <module>
    from .cf_dns import TXTrec
  File "/home/dietpi/cfspflat/cfspflat/cf_dns.py", line 2, in <module>
    import CloudFlare
ModuleNotFoundError: No module named 'CloudFlare'

```

Module "cloudflare" is installed and working.

**Comment by arminsch** [comment]
This is due to an API change of the Cloudflare Python API. See #3 for a fix.

**Comment by Glocktober** [comment]
updates added
